CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE DATABASE keycloak;
CREATE USER keycloak WITH PASSWORD 'keycloak';
ALTER DATABASE keycloak OWNER TO keycloak;

CREATE DATABASE users;
CREATE USER users WITH PASSWORD 'users';
ALTER DATABASE users OWNER TO users;

CREATE DATABASE courses;
CREATE USER courses WITH PASSWORD 'courses';
ALTER DATABASE courses OWNER TO courses;

CREATE DATABASE tasks;
CREATE USER tasks WITH PASSWORD 'tasks';
ALTER DATABASE tasks OWNER TO tasks;
