// Code generated by Constructor annotation processor. DO NOT EDIT.
// versions:
//		go: go1.20.4
//		go-annotation: 0.1.0
//		Constructor: 1.0.0

package routes

import (
	handlers "github.com/YReshetko/it-learning-platform/api-app/internal/http/handlers"
	auth "github.com/YReshetko/it-learning-platform/api-app/internal/http/middlewares/authorization"
)

type RouterOption func(*Router)

func NewRouter(opts ...RouterOption) Router {
	rt := &Router{}
	for _, o := range opts {
		o(rt)
	}

	return *rt
}

func WithAuthHandler(v handlers.Auth) RouterOption {
	return func(rt *Router) {
		rt.authHandler = v
	}
}

func WithAuthService(v auth.Service) RouterOption {
	return func(rt *Router) {
		rt.authService = v
	}
}
