// Code generated by Constructor annotation processor. DO NOT EDIT.
// versions:
//		go: go1.20.4
//		go-annotation: 0.1.0
//		Constructor: 1.0.0

package handlers

import (
	clients "github.com/YReshetko/it-academy-cources/api-app/internal/clients"
)

func NewAuth(client clients.AuthClient) Auth {
	returnValue := Auth{
		client: client,
	}

	return returnValue
}
