// Code generated by Constructor annotation processor. DO NOT EDIT.
// versions:
//		go: go1.20.4
//		go-annotation: 0.1.0
//		Constructor: 1.0.0

package handlers

import (
	clients "github.com/YReshetko/it-learning-platform/api-app/internal/clients"
	mappers "github.com/YReshetko/it-learning-platform/api-app/internal/http/mappers"
	logrus "github.com/sirupsen/logrus"
)

func NewCourses(client clients.CoursesClient, logger *logrus.Entry, technologyMapper mappers.TechnologyMapper) Courses {
	returnValue := Courses{
		client:           client,
		logger:           logger,
		technologyMapper: technologyMapper,
	}

	return returnValue
}

func NewRegistration(client clients.AuthClient, logger *logrus.Entry) Registration {
	returnValue := Registration{
		client: client,
		logger: logger,
	}

	return returnValue
}

func NewSelf(client clients.AuthClient, logger *logrus.Entry) Self {
	returnValue := Self{
		client: client,
		logger: logger,
	}

	return returnValue
}
