// Code generated by Constructor annotation processor. DO NOT EDIT.
// versions:
//		go: go1.20.4
//		go-annotation: 0.1.0
//		Constructor: 1.0.0

package storage

import (
	gorm "gorm.io/gorm"
)

func NewCourseStorage(db *gorm.DB) CourseStorage {
	returnValue := CourseStorage{
		db: db,
	}

	return returnValue
}
