// Code generated by Constructor annotation processor. DO NOT EDIT.
// versions:
//		go: go1.20.4
//		go-annotation: 0.1.0
//		Constructor: 1.0.0

package clients

import (
	config "github.com/YReshetko/it-academy-cources/api-app/internal/config"
)

func NewAuthClient(cfg config.AuthClient) AuthClient {
	returnValue := AuthClient{
		cfg: cfg,
	}
	returnValue.postConstruct()

	return returnValue
}
