// Code generated by Constructor annotation processor. DO NOT EDIT.
// versions:
//		go: go1.20.4
//		go-annotation: 0.1.0
//		Constructor: 1.0.0

package clients

import (
	config "github.com/YReshetko/it-learning-platform/api-app/internal/config"
	logrus "github.com/sirupsen/logrus"
)

func NewAuthClient(cfg config.AuthClient, logger *logrus.Entry) AuthClient {
	returnValue := AuthClient{
		cfg:    cfg,
		logger: logger,
	}
	returnValue.postConstruct()

	return returnValue
}

func NewCoursesClient(cfg config.CoursesClient, logger *logrus.Entry) CoursesClient {
	returnValue := CoursesClient{
		cfg:    cfg,
		logger: logger,
	}
	returnValue.postConstruct()

	return returnValue
}
