// Code generated by Constructor annotation processor. DO NOT EDIT.
// versions:
//		go: go1.20.4
//		go-annotation: 0.1.0
//		Constructor: 1.0.0

package authorization

import (
	clients "github.com/YReshetko/it-academy-cources/api-app/internal/clients"
)

func NewService(client clients.AuthClient) Service {
	returnValue := Service{
		client: client,
	}

	return returnValue
}
