// Code generated by Constructor annotation processor. DO NOT EDIT.
// versions:
//		go: go1.20.4
//		go-annotation: 0.1.0
//		Constructor: 1.0.0

package grpc

import (
	storage "github.com/YReshetko/it-learning-platform/svc-users/internal/storage"
	logrus "github.com/sirupsen/logrus"
)

func NewHandler(logger *logrus.Entry, storage storage.UserStorage) Handler {
	returnValue := Handler{
		logger:  logger,
		storage: storage,
	}

	return returnValue
}
