// Code generated by Constructor annotation processor. DO NOT EDIT.
// versions:
//		go: go1.20.4
//		go-annotation: 0.1.0
//		Constructor: 1.0.0

package grpc

import (
	clients "github.com/YReshetko/it-academy-cources/svc-auth/internal/clients"
	config "github.com/YReshetko/it-academy-cources/svc-auth/internal/config"
)

func NewHandler(keycloakClient *clients.KeycloakClient, userClient *clients.UsersClient) Handler {
	returnValue := Handler{
		keycloakClient: keycloakClient,
		userClient:     userClient,
	}

	return returnValue
}

func NewServer(cfg config.GRPC, handler *Handler) Server {
	returnValue := Server{
		cfg:     cfg,
		handler: handler,
	}

	return returnValue
}
